In [1]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Load processed data
data_path = os.path.join("..", "data", "processed", "processed_data.csv")
df = pd.read_csv(data_path)

# ---------- Basic Info ----------
print("✅ Dataset Info:")
df.info()
print("\n✅ Dataset Shape:", df.shape)
df.head()

✅ Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Columns: 919 entries, director_name to Western
dtypes: float64(914), object(5)
memory usage: 35.3+ MB

✅ Dataset Shape: (5036, 919)

,director_name,actor_1_name,actor_2_name,actor_3_name,movie_title,Action,Action Adventure,Action Adventure Animation Comedy Crime Family Fantasy,Action Adventure Animation Comedy Drama Family Fantasy Thriller,Action Adventure Animation Comedy Drama Family Sci-Fi,...,Mystery Western,Romance,Romance Sci-Fi Thriller,Romance Short,Sci-Fi,Sci-Fi Thriller,Thriller,Thriller War,Thriller Western,Western
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,avatar,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,pirates of the caribbean: at world's end,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,spectre,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,the dark knight rises,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Doug Walker,Doug Walker,Rob Walker,unknown,star wars: episode vii - the force awakens,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
# ---------- Missing Values ----------
print("✅ Missing Values per Column:")
df.isnull().sum()

✅ Missing Values per Column:

director_name       116
actor_1_name        116
actor_2_name        116
actor_3_name        116
movie_title         116
                   ...
Sci-Fi Thriller     116
Thriller            116
Thriller War        116
Thriller Western    116
Western             116
Length: 919, dtype: int64